package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Group -typeSlug group

import "syscall/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = Group{}

func (obj Group) ApplyMatrix4(matrix Matrix4) {
	obj.Call("applyMatrix4", matrix.Value)
}

func (obj Group) Add(m Object3D) {
	obj.Value.Call("add", m.getInternalObject())
}

func (obj Group) Remove(m js.Value) {
	obj.Value.Call("remove", m)
}

func (obj Group) GetObjectById(id int) js.Value {
	return obj.Call("getObjectById", id)
}

// func (obj Group) Copy() Group {
// 	return Group{Object: obj.getInternalObject().Call("copy")}
// }

func (obj Group) ToJSON() js.Value {
	return obj.Value.Call("toJSON")
}

func (obj Group) getInternalObject() js.Value {
	return obj.Value
}

func (obj Group) UpdateMatrix() {
	obj.Call("updateMatrix")
}

func (obj Group) SetPosition(v Vector3) {
	obj.Get("position").Call("copy", v.Value)
}

func (obj Group) SetRotation(euler Euler) {
	obj.Get("rotation").Call("copy", euler.Value)
}

func (obj Group) GetPosition() Vector3 {
	return Vector3{
		Value: obj.Get("position"),
	}
}

func (obj Group) GetRotation() Euler {
	return Euler{
		Value: obj.Get("rotation"),
	}
}