package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName AmbientLight -typeSlug ambient_light

import "syscall/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = AmbientLight{}

func (obj AmbientLight) ApplyMatrix4(matrix Matrix4) {
	obj.Call("applyMatrix4", matrix.Value)
}

func (obj AmbientLight) Add(m Object3D) {
	obj.Value.Call("add", m.getInternalObject())
}

func (obj AmbientLight) Remove(m js.Value) {
	obj.Value.Call("remove", m)
}

func (obj AmbientLight) GetObjectById(id int) js.Value {
	return obj.Call("getObjectById", id)
}

// func (obj AmbientLight) Copy() AmbientLight {
// 	return AmbientLight{Object: obj.getInternalObject().Call("copy")}
// }

func (obj AmbientLight) ToJSON() js.Value {
	return obj.Value.Call("toJSON")
}

func (obj AmbientLight) getInternalObject() js.Value {
	return obj.Value
}

func (obj AmbientLight) UpdateMatrix() {
	obj.Call("updateMatrix")
}

func (obj AmbientLight) SetPosition(v Vector3) {
	obj.Get("position").Call("copy", v.Value)
}

func (obj AmbientLight) SetRotation(euler Euler) {
	obj.Get("rotation").Call("copy", euler.Value)
}

func (obj AmbientLight) GetPosition() Vector3 {
	return Vector3{
		Value: obj.Get("position"),
	}
}

func (obj AmbientLight) GetRotation() Euler {
	return Euler{
		Value: obj.Get("rotation"),
	}
}