package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName TextSprite -typeSlug text_sprite

import "syscall/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = TextSprite{}

func (obj TextSprite) ApplyMatrix4(matrix Matrix4) {
	obj.Call("applyMatrix4", matrix.Value)
}

func (obj TextSprite) Add(m Object3D) {
	obj.Value.Call("add", m.getInternalObject())
}

func (obj TextSprite) Remove(m js.Value) {
	obj.Value.Call("remove", m)
}

func (obj TextSprite) GetObjectById(id int) js.Value {
	return obj.Call("getObjectById", id)
}

// func (obj TextSprite) Copy() TextSprite {
// 	return TextSprite{Object: obj.getInternalObject().Call("copy")}
// }

func (obj TextSprite) ToJSON() js.Value {
	return obj.Value.Call("toJSON")
}

func (obj TextSprite) getInternalObject() js.Value {
	return obj.Value
}

func (obj TextSprite) UpdateMatrix() {
	obj.Call("updateMatrix")
}

func (obj TextSprite) SetPosition(v Vector3) {
	obj.Get("position").Call("copy", v.Value)
}

func (obj TextSprite) SetRotation(euler Euler) {
	obj.Get("rotation").Call("copy", euler.Value)
}

func (obj TextSprite) GetPosition() Vector3 {
	return Vector3{
		Value: obj.Get("position"),
	}
}

func (obj TextSprite) GetRotation() Euler {
	return Euler{
		Value: obj.Get("rotation"),
	}
}