package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// material_method_generator -typeName SpriteMaterial -typeSlug sprite

import "syscall/js"

// Compile-time check that this type implements Material interface.
var _ Material = SpriteMaterial{}

func (m SpriteMaterial) OnBeforeCompile() {
	m.Call("onBeforeCompile")
}

func (m SpriteMaterial) SetValues(values *MaterialParameters) {
	m.Call("setValues", objectify(values))
}

func (m SpriteMaterial) ToJSON(meta interface{}) js.Value {
	return m.Call("toJSON", meta)
}

func (m SpriteMaterial) Clone() {
	m.Call("clone")
}

func (m SpriteMaterial) Copy(source Object3D) {
	m.Call("copy", source.getInternalObject())
}

func (m SpriteMaterial) Dispose() {
	m.Call("dispose")
}

func (m SpriteMaterial) getInternalObject() js.Value {
	return m.Value
}
