package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// geometry_method_generator -typeName BufferGeometry -typeSlug buffer

import "syscall/js"

// Compile-time check that this type implements Geometry interface.
var _ Geometry = BufferGeometry{}

func (g BufferGeometry) ApplyMatrix4(matrix *Matrix4) {
	g.Value.Call("applyMatrix4", matrix)
}

func (g BufferGeometry) RotateX() {
	g.Value.Call("rotateX")
}

func (g BufferGeometry) RotateY() {
	g.Value.Call("rotateY")
}

func (g BufferGeometry) RotateZ() {
	g.Value.Call("rotateZ")
}

func (g BufferGeometry) Translate() {
	g.Value.Call("translate")
}

func (g BufferGeometry) Scale() {
	g.Value.Call("scale")
}

func (g BufferGeometry) LookAt() {
	g.Value.Call("lookAt")
}

func (g BufferGeometry) FromBufferGeometry(geometry Geometry) {
	g.Value.Call("fromBufferGeometry")
}

func (g BufferGeometry) Center() {
	g.Value.Call("center")
}

func (g BufferGeometry) Normalize() BufferGeometry {
	g.Value.Call("normalize")
	return g
}

func (g BufferGeometry) ComputeFaceNormals() {
	g.Value.Call("computeFaceNormals")
}

func (g BufferGeometry) ComputeVertexNormals(areaWeighted bool) {
	g.Value.Call("computeVertexNormals", areaWeighted)
}

func (g BufferGeometry) ComputeFlatVertexNormals() {
	g.Value.Call("computeFlatVertexNormals")
}

func (g BufferGeometry) ComputeMorphNormals() {
	g.Value.Call("computeMorphNormals")
}

func (g BufferGeometry) ComputeLineDistances() {
	g.Value.Call("computeLineDistances")
}

func (g BufferGeometry) ComputeBoundingBox() {
	g.Value.Call("computeBoundingBox")
}

func (g BufferGeometry) ComputeBoundingSphere() {
	g.Value.Call("computeBoundingSphere")
}

func (g BufferGeometry) Merge(geometry Geometry, matrix Matrix4, materialIndexOffset float64) {
	g.Value.Call("merge", geometry.getInternalObject(), matrix.Value, materialIndexOffset)
}

func (g BufferGeometry) MergeMesh(mesh Mesh) {
	g.Value.Call("mergeMesh", mesh.getInternalObject())
}

func (g BufferGeometry) MergeVertices() {
	g.Value.Call("mergeVertices")
}

func (g BufferGeometry) SortFacesByMaterialIndex() {
	g.Value.Call("sortFacesByMaterialIndex")
}

func (g BufferGeometry) ToJSON() js.Value {
	return g.Value.Call("toJSON")
}

// func (g BufferGeometry) Clone() BufferGeometry {
// 	return g.Value.Call("clone")
// }

func (g BufferGeometry) Copy(source Object3D, recursive bool) *BufferGeometry {
	return &BufferGeometry{Value: g.getInternalObject().Call("copy", source.getInternalObject(), recursive)}
}

func (g BufferGeometry) Dispose() {
	g.Value.Call("dispose")
}

func (g BufferGeometry) getInternalObject() js.Value {
	return g.Value
}
