package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// material_method_generator -typeName MeshPhysicalMaterial -typeSlug mesh_physical

import "syscall/js"

// Compile-time check that this type implements Material interface.
var _ Material = MeshPhysicalMaterial{}

func (m MeshPhysicalMaterial) OnBeforeCompile() {
	m.Call("onBeforeCompile")
}

func (m MeshPhysicalMaterial) SetValues(values *MaterialParameters) {
	m.Call("setValues", objectify(values))
}

func (m MeshPhysicalMaterial) ToJSON(meta interface{}) js.Value {
	return m.Call("toJSON", meta)
}

func (m MeshPhysicalMaterial) Clone() {
	m.Call("clone")
}

func (m MeshPhysicalMaterial) Copy(source Object3D) {
	m.Call("copy", source.getInternalObject())
}

func (m MeshPhysicalMaterial) Dispose() {
	m.Call("dispose")
}

func (m MeshPhysicalMaterial) getInternalObject() js.Value {
	return m.Value
}
