package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName DirectionalLight -typeSlug directional_light

import "syscall/js"

// Compile-time check that this type implements Object3D interface.
var _ Object3D = &DirectionalLight{}

func (obj *DirectionalLight) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix.Value)
}

func (obj *DirectionalLight) Add(m Object3D) {
	obj.Value.Call("add", m.getInternalObject())
}

func (obj *DirectionalLight) Remove(m js.Value) {
	obj.Value.Call("remove", m)
}

func (obj *DirectionalLight) GetObjectById(id int) js.Value {
	return obj.Call("getObjectById", id)
}

// func (obj *DirectionalLight) Copy() *DirectionalLight {
// 	return &DirectionalLight{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *DirectionalLight) ToJSON() js.Value {
	return obj.Value.Call("toJSON")
}

func (obj *DirectionalLight) getInternalObject() js.Value {
	return obj.Value
}

func (obj *DirectionalLight) UpdateMatrix() {
	obj.Call("updateMatrix")
}

func (obj *DirectionalLight) SetPosition(v Vector3) {
	obj.Get("position").Call("copy", v.Value)
}

func (obj *DirectionalLight) SetRotation(euler Euler) {
	obj.Get("rotation").Call("copy", euler.Value)
}

func (obj *DirectionalLight) GetPosition() Vector3 {
	return Vector3{
		Value: obj.Get("position"),
	}
}

func (obj *DirectionalLight) GetRotation() Euler {
	return Euler{
		Value: obj.Get("rotation"),
	}
}