package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Mesh -typeSlug mesh

import "syscall/js"

// Compile-time check that this type implements Object3D interface.
// var _ Object3D = &Mesh{}

func (obj *Mesh) ApplyMatrix4(matrix *Matrix4) {
	obj.Call("applyMatrix4", matrix)
}

func (obj *Mesh) Add(m Object3D) {
	obj.Value.Call("add", m)
}

func (obj *Mesh) Remove(m js.Value) {
	obj.Value.Call("remove", m)
}

func (obj *Mesh) GetObjectById(id int) js.Value {
	return obj.Call("getObjectById", id)
}

// func (obj *Mesh) Copy() *Mesh {
// 	return &Mesh{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Mesh) ToJSON() js.Value {
	return obj.Value.Call("toJSON")
}

func (obj *Mesh) getInternalObject() js.Value {
	return obj.Value
}

func (obj *Mesh) UpdateMatrix() {
	obj.Call("updateMatrix")
}
