package three

// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// material_method_generator -materialName {{ .Type }} -materialSlug {{ .Slug }}

import "syscall/js"

// Compile-time check that this type implements Material interface.
var _ Material = {{ .Type }}{}

func (m {{ .Type }}) OnBeforeCompile() {
	m.Call("onBeforeCompile")
}

func (m {{ .Type }}) SetValues(values MaterialParameters) {
	m.Call("setValues", objectify(values))
}

func (m {{ .Type }}) ToJSON(meta interface{}) js.Value {
	return m.Call("toJSON", meta)
}

func (m {{ .Type }}) Clone() {
	m.Call("clone")
}

func (m {{ .Type }}) Copy(source Object3D) {
	m.Call("copy", source)
}

func (m {{ .Type }}) Dispose() {
	m.Call("dispose")
}

func (m {{ .Type }}) getInternalObject() js.Value {
	return m.Value
}
